name: Kalvachev
favicon: null
layout_spectrum: 0.2587756880093366
typography_spectrum: 0.718511565355584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b0d'
    - '#375989'
    - '#abada5'
    - '#cf2911'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
